application_root: ""
cors: true
log_level: "DEBUG"
listen_port: 8080

# jwt
jwt_private_key: "./config/jwt/jwt.key"
jwt_public_key: "./config/jwt/jwt.key.pub"
jwt_algorithm: "RS256"
access_token_validation_period: "1h"
refresh_token_validation_period: "30d"

# mysql config
mysql_host: "127.0.0.1"
mysql_port: 3306
mysql_database: "gms"
mysql_user: "root"
mysql_password: "123456"
mysql_charset: "utf8mb4"
mysql_pool_size: 32
