application_root: ""                # set to path if the backend is not serve at the root eg. set to "/api/1.0" if hosted at "http://example.com/api/1.0/"
cors: true                          # allow CORS
log_level: "DEBUG"                  # "DEBUG" "INFO" "WARNING" "ERROR"
listen_port: 8080                   # listen port
admin_username: superuser@test.com  # admin username, must be in email format for web login
admin_password: resurepus           # admin initial password, can be set later in the web

# jwt
jwt_private_key: "./config/jwt/jwt.key"     # JWT private key
jwt_public_key: "./config/jwt/jwt.key.pub"  # JWT public key
jwt_algorithm: "RS256"                      # JWT algorithm, must be consistent with the key pair format
access_token_validation_period: "1h"        # The expiration time of the access token
refresh_token_validation_period: "30d"      # The expiration time of the refresh token, this controls how long the user is able to stay logged in between sessions if remember me option is checked. 

# mysql config
mysql_host: "127.0.0.1"             # MySQL host
mysql_port: 3306                    # MySQL port
mysql_database: "gms"               # MySQL database name
mysql_user: "gms"                   # MySQL username
mysql_password: "123456"            # MySQL password
mysql_charset: "utf8mb4"            # MySQL charset (not used currently)
mysql_pool_size: 32                 # MySQL connection pool size (not used currently)
